### ISSUE TITLE
RuntimeWarning: coroutine was never awaited

### ISSUE THREAD

**Issue by tjorim** [sca075/valetudo_vacuum_camera#135]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py:197
integration: Valetudo Vacuum Camera (documentation, issues)
First occurred: 06:21:32 (1 occurrences)
Last logged: 06:21:32

/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py:197: RuntimeWarning: coroutine 'ValetudoConnector.async_decode_mqtt_payload' was never awaited self._mqtt_vac_err = self._payload

### What version of an integration has described problem?

2024.05.0

### What vacuum model do you have problems with?

n/a

### Please firmware installed on your Vacuum.

n/a

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

2024.05.1

### What type of installation are you running?

Home Assistant OS

**Comment by tjorim** [comment]
I just noticed I didn't submit my comment on #128:
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/1294876/ddeccb60-d4c2-4565-9384-a966c3dc20d0)
Seems already fixed in #134.

**Comment by sca075** [comment]
@tjorim did forgot the await on that line, I did open the PR [24d7a82](https://github.com/sca075/valetudo_vacuum_camera/pull/134/commits/24d7a82a972c32cb76d700e6bb6e3cb0681a9b98)and it is going to be fix as late today.
It is about the errors decoding correct?

**Comment by tjorim** [comment]
I don't have any decoding errors, just the missing await (coroutine 'ValetudoConnector.async_decode_mqtt_payload' was never awaited).

**Comment by sca075** [comment]
@tjorim  yes it is because the async_decode_mqtt_payload need to be await at line 196 of the conector.py as I wrote above I'm aware and it was corrected, but not yet publish in the new release that I'm working on.
I need to finish some check for the calibration data when changing the aspect ratio of the image.. as soon I'm done will be out the 2025.05.1 with the correction for this.
I discussed this issue with the core guys and the async_decode_mqtt_payload was introduced as per HA try to convert the data out from MQTT.. there are two option to solve it, and I went for the home made one as it normally works when awaited.
Please give me a couple of hours and I will publish the code, if you want and have time to test the code.. just replace the connector.py with the one on the PR.
Thanks again :)

**Comment by sca075** [comment]
@tjorim just released 2024.05.1 with the fix for this issue ;) thanks once again.
