### ISSUE TITLE
Migration error on boot upgrading to v1.5.7

### ISSUE THREAD

**Issue by Cellivar** [sca075/valetudo_vacuum_camera#77]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

After upgrading via HACS the plugin stopped working. I get an error in the log on startup. 

I can click the 'configure' button, however all of my settings show up as defaults.

I have extensive, painstakingly tuned settings that would take a few hours to put back from scratch, and would really really appreciate not having to do that again 🙂 

### What version of an integration has described problem?

v1.5.7

### What vacuum model do you have problems with?

N/A

### Please firmware installed on your Vacuum.

N/A

### What version of Home Assistant do you use?

2023.11.3

### What type of installation are you running?

Home Assistant Container

### Camera's settings.

```yaml
I can't get them :(
```

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:650
First occurred: 01:04:43 (3 occurrences)
Last logged: 01:04:43

Error migrating entry Valetudo Camera for valetudo_vacuum_camera
Error migrating entry Roboterstaubsauger Camera for valetudo_vacuum_camera
Error migrating entry Hygieia Camera for valetudo_vacuum_camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 650, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/__init__.py", line 172, in async_migrate_entry
    new_options = await update_options(old_options, tmp_option)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/common.py", line 151, in update_options
    updated_options[key] = bk_options[key]
                           ~~~~~~~~~~^^^^^
KeyError: 'get_svg_file'
```

**Comment by sca075** [comment]
@Cellivar I just tested the migration process from 1.4.8 to 1.5.7.4 (that I'm going to release in a couple of minutes), the config entry 2.1 can be now converted without any problem to 2.2.
From what version did you start the conversion? Also, if you like this project please consider to star it to get always updated on new evolutions ;)

**Comment by sca075** [comment]
@Cellivar the version v1.5.7.4 is now released. There is now the auto trim function that should simply the setup of the camera on this newer versions. Of course the colour settings can be.. to be redo.. (if the camera was deleted).
In general this fix the migration issue you kindly reported, anyhow I'm at your disposal for anything else and await your kind confirmation.

**Comment by sca075** [comment]
@Cellivar added to the pre-release check list a test to avoid this in the future. Thanks once again for the hint.

**Comment by Cellivar** [comment]
Wow thank you for the really fast fix! I just applied `v1.5.7.4` and can confirm that the reported issue is fixed, however I encountered a new problem.

I previously was running Home Assistant with a limit of 756MB of RAM. After updating to the latest version there's a ~1,400MB spike of memory use during startup, then the system settles down to around 780MB. This is what the chart looks like.

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/1441553/37a4b958-c4ab-4e48-b4f7-1822563d637c)

I have some extra space in my cluster so I can work around this problem by increasing the limit, but this is a much higher resting state than before. I don't have time this weekend to test further by enabling and disabling things to confirm that it's definitely this integration.

If you have any suggestions on ways I can help you understand what my system is doing I'm very happy to collect more logs or otherwise. I'm a software developer, but I don't write Python code, so I'm not familiar with those tools :)

**Comment by sca075** [comment]
@Cellivar any help here is appreciated. I do not know from what version you updated so I can't make a comparison. 
Recently I added a couple of new functions (auto-cropping is one of them) and also I wrote a function to check in what room is the robot (those are the biggest change).
The auto trimming of the image as the robot position check at startup uses a little more memory than before but the memory should free after that (except for the buffered base image that isn't redrawn in case the LiDAR detects "new walls").

On the v1.5.8 I plan to keep the memory constant to the minimum after the camera boot(this is what I'm actually checking with the new introduction of the memory limit)

This checks the size of NP array multiplied the number of steps to complete the image (as I'm not sure if Numpy is actually freeing the memory). In reality I'm deleting all unnecessary arrays on the draw functions) that I had to write by my own as per home assistant OS do not support OpenCV. 

Any logs from the Camera and details of system where you run HA would be helpful to warrant that this project goes ahead improving. Would you be so kind to open a discussion so that we can trace this please 😉

**Comment by sca075** [comment]
Camera Memory usage in GB: 0.63, 8.24% of Total. (I have to Camera's on the PI4 and this need to be so 1.2GB peak max on my test environment).

**Comment by Cellivar** [comment]
Hey, I'm sorry I wasn't able to get back to you with more testing data.

I wanted to confirm that the last few updates have helped a lot and everything is running very smooth now. Thank you so much for putting the time in to test things and for making such an excellent addon!
