### ISSUE TITLE
Invalid Calibration Error with any version above 1.5.7.1

### ISSUE THREAD

**Issue by duffmiester** [sca075/valetudo_vacuum_camera#79]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Every time I update to any version beyond 1.5.7.1 I get the error 'Invalid calibration, please check your configuration' on the camera card and no map is displayed. This happens on 1.5.7.2 - 1.5.7.5. 

I tried reinstalling multiple times.

### What version of an integration has described problem?

1.5.7.5

### What was the last working version of an integration?

1.5.7.1

### What vacuum model do you have problems with?

Xiaomi 1C

### Please firmware installed on your Vacuum.

2023.12.0

### What version of Home Assistant do you use?

core-2024.2.1

### What type of installation are you running?

Home Assistant OS

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
2024-02-10 17:31:59.879 WARNING (jimmy_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] Memory shortage error: Not enough memory available (Margin: 1310.9 MiB)
```

**Comment by sca075** [comment]
@duffmiester I think I will disable this.. it was just an attempt to understand an issue reported in a discussion but eventually this is creating a lot of issue (the strange thing is that without this "memory limit check" it should work) I also noticed since 2024.2.1 there are other more important issue to care of (the CPU of core is reading our CPU calculation apparently probably a call to to PSUTIL too much.).
I really apologise for this.. I will work now on the v1.5.8 and revert those changes (or make them available optionally).
and thanks.. I don't why but receiving "warning" from you.. feels good.

**Comment by duffmiester** [comment]
I will standby ready to test 1.5.8 for you when it is ready. Thanks for your continued work on this project, it is really useful

**Comment by sca075** [comment]
@duffmiester if you would be so kind to do me the favour to test the last commit [6e98dba](https://github.com/sca075/valetudo_vacuum_camera/commit/6e98dba807c1c8ac9b45563fc7e3db27c8731609)
Simply re-download the "main" form the version's that HACS propose, as there are no updates (I'm still working on the new version), the v1.5.7.1 is still available on HACS. The modifications done till now should address the issue you kindly raised. 
- No check of the memory.
- Review of the CPU counters done.
- Some little / minor refactoring of the code was done on the image_handler too (and the memory usage is going down).
Tested till now with both the vacuums I have, this should be already working for you. 
If all it's okay please star the project and and just a tong up on this means we are on the right way.

Of course, if you have time for that, then tanks in advance for the cooperation, and soon V1.5.8 will be release.

**Comment by duffmiester** [comment]
Have tested with 'main' and it is working now. 

Thanks for the quick response!

**Comment by sca075** [comment]
@duffmiester I fixed also the invalid calibration error, apparently on V1.5.8, the MQTT data available (also when the vacuum isn't connected) was creating the handler to return none therefore the camera attributes didn't got the last available data in mqtt.. if the vacuum do not move, well is because it isn't connected so locating the vacuum will help to know it, but the camera will always startup when there are data in MQTT.  ;)

**Comment by sca075** [comment]
@duffmiester v1.5.8 is now available, hope you will enjoy it at your disposal for any future requirements or ideas.

**Comment by duffmiester** [comment]
Installed 1.5.8 and seems to be working fine so far. Thanks as always for the help :-)
