### ISSUE TITLE
Configuring an alerady exisiting entry yields empty fields

### ISSUE THREAD

**Issue by Skeletorjus** [sca075/valetudo_vacuum_camera#9]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

All the fields are empty if I try to (re)configure an entry after the initial configuration, making it impossible to tune the settings.

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/9031934/720043c9-8f93-4ef3-bbdf-56ac4b0931e9)

### What version of an integration has described problem?

v1.1.9

### What vacuum model do you have problems with?

Roborock.S5

### Please firmware installed on your Vacuum.

2023.02.0

### What version of Home Assistant do you use?

core-2023.8.1

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
N/A
```

**Comment by sca075** [comment]
Thanks for the feedback, will check it and report back when will found the issue.

**Comment by sca075** [comment]
I found the problem, will work out a solution for this as high priority. I guess we get it work within tomorrow. Meanwhile would be so kind to delete the current configured camera and set it up again? This apparently is a working work around.

**Comment by sca075** [comment]
@Skeletorjus, fixed.. I will release version 1.1.9_1 within this night.. I will fully re-test it, I think there was a mistake on my side on the testing procedure I use and it passed not noticed because on the test environment I had already "somehow" some options data in the config_registry (due to the tests I did). By cleaning up the registry I could reproduced the issue. The fix is already tested and it works. As soon I'm done with it I will let you know, thanks once again for raising up this..

**Comment by Skeletorjus** [comment]
@sca075, that's fantastic! Thanks a bunch for the quick fix 👍

**Comment by sca075** [comment]
@Skeletorjus as promised release v1.1.9_1 is out with the fix for the reported issue. I will keep open this till I get your kind confirmation that the issue is resolved at your side (from the tests done till now on both PI4 test HA and HA main instance on server, both supervised) there should be no problem. You are using a Roborock.S5, therefore if there is any issue with the image rendering please let me know ;) thanks once again.

**Comment by Skeletorjus** [comment]
Confirmed working in v1.1.9_1, so I'm closing this.
Thanks! 😊
